### ISSUE TITLE
Unable to connect to ollama (installed via flatpak)

### ISSUE THREAD

**Issue by braindotai** [Jeffser/Alpaca#107]
**Describe the bug**
Installing Alpaca for the first time on my system... (Arch Linux). I am unable to enter the ollama server url and get a conneciton.

[Screencast from 2024-06-21 18-43-48.webm](https://github.com/Jeffser/Alpaca/assets/50226064/4544c809-adfd-4574-8823-4d58fd7ebe02)

**Expected behavior**
Dropping ollama server localhost url and alpaca gets connected to ollama.

Let me if there's any prerequisites that I am missing.

**Comment by loulou64490** [comment]
Same issue

**Comment by Jeffser** [comment]
Hi, what does the terminal output if you launch Ollama from there? `flatpak run com.jeffser.Alpaca`

**Comment by braindotai** [comment]
```
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
[GIN] 2024/06/24 - 13:37:18 | 200 |      17.032µs |       127.0.0.1 | GET      "/"
[GIN] 2024/06/24 - 13:37:18 | 200 |      66.536µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/06/24 - 13:37:24 | 200 |      28.103µs |       127.0.0.1 | GET      "/"
[GIN] 2024/06/24 - 13:37:24 | 200 |      59.664µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/06/24 - 13:37:36 | 200 |      16.842µs |       127.0.0.1 | GET      "/"
[GIN] 2024/06/24 - 13:37:36 | 200 |      59.042µs |       127.0.0.1 | GET      "/api/tags"

(alpaca:2): Gtk-CRITICAL **: 13:37:47.309: gtk_accessible_text_get_contents: assertion 'end >= start' failed
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
[GIN] 2024/06/24 - 13:37:53 | 200 |      32.902µs |       127.0.0.1 | GET      "/"
[GIN] 2024/06/24 - 13:37:53 | 200 |     103.256µs |       127.0.0.1 | GET      "/api/tags"
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
[GIN] 2024/06/24 - 13:38:05 | 200 |      31.039µs |       127.0.0.1 | GET      "/"
[GIN] 2024/06/24 - 13:38:05 | 200 |      63.902µs |       127.0.0.1 | GET      "/api/tags"
```
@Jeffser

**Comment by Jeffser** [comment]
I think it works now, I'm not sure what made it work but it does work (at least for me)

**Comment by braindotai** [comment]
I tried reinstalling it, still unable to connect to ollama. There must be something I am doing differently right? I mean flatpaks are supposed to be working same as per my understandind.

**Comment by Jeffser** [comment]
Sorry I didn't mention it, all the changes are coming for the next release

**Comment by OggyP** [comment]
Hi, I'm having this issue myself, running curl the ollama instance works:
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama3.1",
  "prompt":"Why is the sky blue?"
}
```
Ollama Logs:
```
[GIN] 2024/08/11 - 22:40:30 | 200 |  9.443821808s |       127.0.0.1 | POST     "/api/generate"
```

However when running Alpaca it is able to start and see listed model but can't generate anything:
```
INFO    [main.py | main] Alpaca version: 1.1.0
Exception in thread Thread-2 (generate_chat_title):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/Alpaca/alpaca/window.py", line 677, in generate_chat_title
    new_chat_name = json.loads(response.text)["response"].strip().removeprefix("Title: ").removeprefix("title: ").strip('\'"').replace('\n', ' ').title().replace('\'S', '\'s')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
ERROR   [window.py | connection_error] Connection error
```

Ollama Logs for Alpaca:
```
[GIN] 2024/08/11 - 22:42:19 | 200 |     293.859µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/08/11 - 22:42:19 | 200 |     276.837µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/08/11 - 22:42:24 | 404 |      17.884µs |       127.0.0.1 | GET      "/api/chat"
[GIN] 2024/08/11 - 22:42:24 | 404 |       7.003µs |       127.0.0.1 | GET      "/api/generate"
```

It seems that Alpaca is somehow sending a GET request instead of a POST request and ollama responds with a 404.
