### ISSUE TITLE
Alpaca from flathub fails to start: No module named 'lxml'

### ISSUE THREAD

**Issue by akhilman** [Jeffser/Alpaca#108]
**Describe the bug**
Alpaca 0.9.6 installed from Flathub fails to start.
```
--> flatpak run com.jeffser.Alpaca
Traceback (most recent call last):
  File "/app/bin/alpaca", line 45, in <module>
    from alpaca import main
  File "/app/share/Alpaca/alpaca/main.py", line 27, in <module>
    from .window import AlpacaWindow
  File "/app/share/Alpaca/alpaca/window.py", line 24, in <module>
    import json, requests, threading, os, re, base64, sys, gettext, locale, webbrowser, subprocess, uuid, shutil, tarfile, tempfile, docx
  File "/app/lib/python3.11/site-packages/docx/__init__.py", line 11, in <module>
    from docx.api import Document
  File "/app/lib/python3.11/site-packages/docx/api.py", line 12, in <module>
    from docx.package import Package
  File "/app/lib/python3.11/site-packages/docx/package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "/app/lib/python3.11/site-packages/docx/opc/package.py", line 9, in <module>
    from docx.opc.part import PartFactory
  File "/app/lib/python3.11/site-packages/docx/opc/part.py", line 9, in <module>
    from docx.opc.oxml import serialize_part_xml
  File "/app/lib/python3.11/site-packages/docx/opc/oxml.py", line 14, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

**Expected behavior**
See the main window.

**Additional context**
Flathub commit: b2809a0630bd3fb30a643b467086b15e2b94149c346d3c943b673a6005318309
Tested in Archlinux and OpenSUSE MicroOS.

**Comment by PanIntegralus** [comment]
Can confirm, current workaround is downgrading to previous version.

**Comment by Jeffser** [comment]
Hi thanks for the report, I don't know why it works only on my main computer, I tested it on a laptop and it doesn't work, I just removed the DOCX code for now, it should be up on flathub in an hour or so.
