### ISSUE TITLE
Error when launching Alpaca

### ISSUE THREAD

**Issue by MaledictYtb** [Jeffser/Alpaca#174]
**Describe the bug**
The app doesn't start

**Expected behavior**
The app should start

**Screenshots**
```
INFO    [main.py | main] Alpaca version: 1.0.2
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/main.py", line 49, in do_activate
    win = AlpacaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 1579, in __init__
    if self.verify_connection() is False: self.connection_error()
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 784, in verify_connection
    response = connection_handler.simple_get(f"{connection_handler.url}/api/tags")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/connection_handler.py", line 16, in simple_get
    return requests.get(connection_url, headers=get_headers(False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:11434/api/tags'
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/window.py", line 406, in model_search_changed
    row.set_visible(re.search(entry.get_text(), '{} {} {}'.format(row.get_title(), (_("image") if self.available_models[key]['image'] else " "), row.get_subtitle()), re.IGNORECASE))
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_visible'
INFO    [window.py | closing_app] Closing app...
INFO    [local_instance.py | stop] Stopping Alpaca's Ollama instance

```

**Additional context**
I think it's related to the app not connecting to ollama running on my PC

**Comment by MaledictYtb** [comment]
Ok so the code to connect to ollama is really bad. It doesn't tell when there's an error. Here's the error I have now : 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/window.py", line 297, in change_remote_url
    if self.verify_connection() == False:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 784, in verify_connection
    response = connection_handler.simple_get(f"{connection_handler.url}/api/tags")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/connection_handler.py", line 16, in simple_get
    return requests.get(connection_url, headers=get_headers(False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/tags (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))


```

**Comment by MaledictYtb** [comment]
I've got it to work by updating ollama.
