### ISSUE TITLE
Cannot get past the disclaimer message

### ISSUE THREAD

**Issue by splice11** [Jeffser/Alpaca#294]
**Describe the bug**
I tried uninstalling and clearning flatpak data, but every time I open alpaca I cannot press "Close" on the disclaimer screen.

**Expected behavior**
To be able to close the disclaimer window

**Screenshots**
![Screenshot_20240911_111459](https://github.com/user-attachments/assets/f8fc7c38-29f8-44b9-9265-7a4952ada894)

**Debugging information**
I can't access this, maybe there is a log file somewhere I can upload. But here is the flatpak console:
```
nobaradesk@nobara-desk:~$ flatpak run com.jeffser.Alpaca
INFO    [main.py | main] Alpaca version: 2.0.0
INFO    [connection_handler.py | start] Starting Alpaca's Ollama instance...
INFO    [connection_handler.py | start] Started Alpaca's Ollama instance
Exception in thread Thread-1 (prepare_alpaca):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
2024/09/11 11:14:38 routes.go:1125: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:true OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11435 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/nobaradesk/.var/app/com.jeffser.Alpaca/data/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-09-11T11:14:38.278+03:00 level=INFO source=images.go:753 msg="total blobs: 0"
time=2024-09-11T11:14:38.278+03:00 level=INFO source=images.go:760 msg="total unused blobs removed: 0"
  File "/usr/lib/python3.11/threading.py", line 982, in run
time=2024-09-11T11:14:38.278+03:00 level=INFO source=routes.go:1172 msg="Listening on 127.0.0.1:11435 (version 0.3.9)"
    self._target(*self._args, **self._kwargs)
  File "/app/share/Alpaca/alpaca/window.py", line 798, in prepare_alpaca
time=2024-09-11T11:14:38.278+03:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu file=build/linux/x86_64/cpu/bin/libggml.so.gz
    self.ollama_instance = connection_handler.instance(local_port, remote_url, remote, tweaks, overrides, bearer_token, idle_timer_delay)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/connection_handler.py", line 40, in __init__
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu file=build/linux/x86_64/cpu/bin/libllama.so.gz
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu file=build/linux/x86_64/cpu/bin/ollama_llama_server.gz
    self.start()
  File "/app/share/Alpaca/alpaca/connection_handler.py", line 111, in start
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx file=build/linux/x86_64/cpu_avx/bin/libggml.so.gz
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx file=build/linux/x86_64/cpu_avx/bin/libllama.so.gz
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx file=build/linux/x86_64/cpu_avx/bin/ollama_llama_server.gz
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx2 file=build/linux/x86_64/cpu_avx2/bin/libggml.so.gz
    logger.info('Ollama version: {}'.format(v_str.split('client version is ')[1].strip()))
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
time=2024-09-11T11:14:38.278+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx2 file=build/linux/x86_64/cpu_avx2/bin/libllama.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx2 file=build/linux/x86_64/cpu_avx2/bin/ollama_llama_server.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v11 file=build/linux/x86_64/cuda_v11/bin/libggml.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v11 file=build/linux/x86_64/cuda_v11/bin/libllama.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v11 file=build/linux/x86_64/cuda_v11/bin/ollama_llama_server.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v12 file=build/linux/x86_64/cuda_v12/bin/libggml.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v12 file=build/linux/x86_64/cuda_v12/bin/libllama.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v12 file=build/linux/x86_64/cuda_v12/bin/ollama_llama_server.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=rocm_v60102 file=build/linux/x86_64/rocm_v60102/bin/libggml.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=rocm_v60102 file=build/linux/x86_64/rocm_v60102/bin/libllama.so.gz
time=2024-09-11T11:14:38.279+03:00 level=DEBUG source=payload.go:182 msg=extracting variant=rocm_v60102 file=build/linux/x86_64/rocm_v60102/bin/ollama_llama_server.gz
libEGL warning: wayland-egl: could not open /dev/dri/renderD128 (No such file or directory)
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/window.py", line 332, in model_search_changed
    for model in list(self.model_manager.available_list):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'available_list'
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/cpu/ollama_llama_server
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/cpu_avx/ollama_llama_server
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/cpu_avx2/ollama_llama_server
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/cuda_v11/ollama_llama_server
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/cuda_v12/ollama_llama_server
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/rocm_v60102/ollama_llama_server
time=2024-09-11T11:14:44.534+03:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cuda_v12 rocm_v60102 cpu cpu_avx cpu_avx2 cuda_v11]"
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=payload.go:45 msg="Override detection logic by setting OLLAMA_LLM_LIBRARY"
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=sched.go:105 msg="starting llm scheduler"
time=2024-09-11T11:14:44.534+03:00 level=INFO source=gpu.go:200 msg="looking for compatible GPUs"
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=gpu.go:86 msg="searching for GPU discovery libraries for NVIDIA"
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=gpu.go:468 msg="Searching for GPU library" name=libcuda.so*
time=2024-09-11T11:14:44.534+03:00 level=DEBUG source=gpu.go:491 msg="gpu library search" globs="[/app/lib/ollama/libcuda.so* /app/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/sdk/llvm15/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/ollama/libcuda.so* /app/plugins/AMD/lib/ollama/libcuda.so* /usr/local/cuda*/targets/*/lib/libcuda.so* /usr/lib/*-linux-gnu/nvidia/current/libcuda.so* /usr/lib/*-linux-gnu/libcuda.so* /usr/lib/wsl/lib/libcuda.so* /usr/lib/wsl/drivers/*/libcuda.so* /opt/cuda/lib*/libcuda.so* /usr/local/cuda/lib*/libcuda.so* /usr/lib*/libcuda.so* /usr/local/lib*/libcuda.so*]"
time=2024-09-11T11:14:44.535+03:00 level=DEBUG source=gpu.go:525 msg="discovered GPU libraries" paths=[]
time=2024-09-11T11:14:44.535+03:00 level=DEBUG source=gpu.go:468 msg="Searching for GPU library" name=libcudart.so*
time=2024-09-11T11:14:44.535+03:00 level=DEBUG source=gpu.go:491 msg="gpu library search" globs="[/app/lib/ollama/libcudart.so* /app/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/sdk/llvm15/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/ollama/libcudart.so* /app/plugins/AMD/lib/ollama/libcudart.so* /home/nobaradesk/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama3125758898/runners/cuda*/libcudart.so* /usr/local/cuda/lib64/libcudart.so* /usr/lib/x86_64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/x86_64-linux-gnu/libcudart.so* /usr/lib/wsl/lib/libcudart.so* /usr/lib/wsl/drivers/*/libcudart.so* /opt/cuda/lib64/libcudart.so* /usr/local/cuda*/targets/aarch64-linux/lib/libcudart.so* /usr/lib/aarch64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/aarch64-linux-gnu/libcudart.so* /usr/local/cuda/lib*/libcudart.so* /usr/lib*/libcudart.so* /usr/local/lib*/libcudart.so*]"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=gpu.go:525 msg="discovered GPU libraries" paths="[/app/lib/ollama/libcudart.so.12.4.99 /app/lib/ollama/libcudart.so.11.3.109]"
cudaSetDevice err: 35
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=gpu.go:537 msg="Unable to load cudart" library=/app/lib/ollama/libcudart.so.12.4.99 error="your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
cudaSetDevice err: 35
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=gpu.go:537 msg="Unable to load cudart" library=/app/lib/ollama/libcudart.so.11.3.109 error="your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
time=2024-09-11T11:14:44.536+03:00 level=WARN source=amd_linux.go:59 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:127 msg="detected CPU /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/1/properties"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:217 msg="mapping amdgpu to drm sysfs nodes" amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties vendor=4098 device=29663 unique_id=0
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:251 msg=matched amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties drm=/sys/class/drm/card1/device
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:283 msg="amdgpu memory" gpu=0 total="10.0 GiB"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_linux.go:284 msg="amdgpu memory" gpu=0 available="9.2 GiB"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/lib/ollama"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/lib"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/GL/default/lib"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/openh264/extra"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/openh264/extra"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/sdk/llvm15/lib"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/GL/default/lib"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/ollama"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/plugins/AMD/lib/ollama"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /opt/rocm/lib"
time=2024-09-11T11:14:44.536+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib64"
time=2024-09-11T11:14:44.537+03:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/share/ollama/lib/rocm"
time=2024-09-11T11:14:44.537+03:00 level=WARN source=amd_linux.go:395 msg="amdgpu detected, but no compatible rocm library found.  Either install rocm v6, or follow manual install instructions at https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install"
time=2024-09-11T11:14:44.537+03:00 level=WARN source=amd_linux.go:322 msg="unable to verify rocm library, will use cpu" error="no suitable rocm found, falling back to CPU"
time=2024-09-11T11:14:44.537+03:00 level=INFO source=gpu.go:347 msg="no compatible GPUs were discovered"
time=2024-09-11T11:14:44.537+03:00 level=INFO source=types.go:107 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="31.2 GiB" available="24.3 GiB"

```

**Comment by F-U-B-AR** [comment]
I had the same issue, I just kept clicking the greyed-out "close" button over and over again and it finally closed it. but now alpaca is stuck on "loading instances" when It tries finding the local ollama server

**Comment by Jeffser** [comment]
Hi thanks for the report, the button is grayed out because the Ollama instance isn't ready yet, I change the behavior so that it shows the launch progress bar when you close the welcome dialog instead of just graying out the button
https://github.com/Jeffser/Alpaca/commit/f46d16d2570e13f408c632d33a47b4ae06fc9509

Of course this doesn't fix the main issue, your instance is failing to launch, I will look into that too

**Comment by Jeffser** [comment]
The newest version should fix this issue, please test it, thanks

**Comment by splice11** [comment]
Just updated and yes the dialog can be closed. Thank you.

**Comment by Jeffser** [comment]
no problem thank you for the report!
