### ISSUE TITLE
Can't load image for recognition

### ISSUE THREAD

**Issue by kozak23** [Jeffser/Alpaca#300]
**Describe the bug**
When trying to upload image for recognition it doesn't load. Model does not see ("is blind") image or it's not showing on chat. I'm using Moondream model. Tried both versions. Edited: Tried Llava, does not load too.

**Expected behavior**
Load and recognize image.

**Debugging information**
```
INFO	[main.py | main] Alpaca version: 2.0.0
INFO	[connection_handler.py | start] Starting Alpaca's Ollama instance...
INFO	[connection_handler.py | start] Started Alpaca's Ollama instance
2024/09/12 09:03:12 routes.go:1125: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES:0 HSA_OVERRIDE_GFX_VERSION:11.0.0 OLLAMA_DEBUG:true OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11435 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/kozak23/.var/app/com.jeffser.Alpaca/data/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-09-12T09:03:12.998+01:00 level=INFO source=images.go:753 msg="total blobs: 11"
time=2024-09-12T09:03:12.998+01:00 level=INFO source=images.go:760 msg="total unused blobs removed: 0"
time=2024-09-12T09:03:12.999+01:00 level=INFO source=routes.go:1172 msg="Listening on 127.0.0.1:11435 (version 0.3.9)"
time=2024-09-12T09:03:12.999+01:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu file=build/linux/x86_64/cpu/bin/libggml.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu file=build/linux/x86_64/cpu/bin/libllama.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu file=build/linux/x86_64/cpu/bin/ollama_llama_server.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx file=build/linux/x86_64/cpu_avx/bin/libggml.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx file=build/linux/x86_64/cpu_avx/bin/libllama.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx file=build/linux/x86_64/cpu_avx/bin/ollama_llama_server.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx2 file=build/linux/x86_64/cpu_avx2/bin/libggml.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx2 file=build/linux/x86_64/cpu_avx2/bin/libllama.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cpu_avx2 file=build/linux/x86_64/cpu_avx2/bin/ollama_llama_server.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v11 file=build/linux/x86_64/cuda_v11/bin/libggml.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v11 file=build/linux/x86_64/cuda_v11/bin/libllama.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v11 file=build/linux/x86_64/cuda_v11/bin/ollama_llama_server.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v12 file=build/linux/x86_64/cuda_v12/bin/libggml.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v12 file=build/linux/x86_64/cuda_v12/bin/libllama.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=cuda_v12 file=build/linux/x86_64/cuda_v12/bin/ollama_llama_server.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=rocm_v60102 file=build/linux/x86_64/rocm_v60102/bin/libggml.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=rocm_v60102 file=build/linux/x86_64/rocm_v60102/bin/libllama.so.gz
time=2024-09-12T09:03:12.999+01:00 level=DEBUG source=payload.go:182 msg=extracting variant=rocm_v60102 file=build/linux/x86_64/rocm_v60102/bin/ollama_llama_server.gz
INFO	[connection_handler.py | start] Ollama version: 0.3.9
INFO	[connection_handler.py | request] GET : http://127.0.0.1:11435/api/tags
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/cpu/ollama_llama_server
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/cpu_avx/ollama_llama_server
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/cpu_avx2/ollama_llama_server
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/cuda_v11/ollama_llama_server
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/cuda_v12/ollama_llama_server
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:71 msg="availableServers : found" file=/home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/rocm_v60102/ollama_llama_server
time=2024-09-12T09:03:25.166+01:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cuda_v11 cuda_v12 rocm_v60102 cpu cpu_avx cpu_avx2]"
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=payload.go:45 msg="Override detection logic by setting OLLAMA_LLM_LIBRARY"
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=sched.go:105 msg="starting llm scheduler"
time=2024-09-12T09:03:25.166+01:00 level=INFO source=gpu.go:200 msg="looking for compatible GPUs"
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=gpu.go:86 msg="searching for GPU discovery libraries for NVIDIA"
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=gpu.go:468 msg="Searching for GPU library" name=libcuda.so*
time=2024-09-12T09:03:25.166+01:00 level=DEBUG source=gpu.go:491 msg="gpu library search" globs="[/app/lib/ollama/libcuda.so* /app/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/sdk/llvm15/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/ollama/libcuda.so* /app/plugins/AMD/lib/ollama/libcuda.so* /usr/local/cuda*/targets/*/lib/libcuda.so* /usr/lib/*-linux-gnu/nvidia/current/libcuda.so* /usr/lib/*-linux-gnu/libcuda.so* /usr/lib/wsl/lib/libcuda.so* /usr/lib/wsl/drivers/*/libcuda.so* /opt/cuda/lib*/libcuda.so* /usr/local/cuda/lib*/libcuda.so* /usr/lib*/libcuda.so* /usr/local/lib*/libcuda.so*]"
time=2024-09-12T09:03:25.167+01:00 level=DEBUG source=gpu.go:525 msg="discovered GPU libraries" paths=[]
time=2024-09-12T09:03:25.167+01:00 level=DEBUG source=gpu.go:468 msg="Searching for GPU library" name=libcudart.so*
time=2024-09-12T09:03:25.167+01:00 level=DEBUG source=gpu.go:491 msg="gpu library search" globs="[/app/lib/ollama/libcudart.so* /app/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/sdk/llvm15/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/ollama/libcudart.so* /app/plugins/AMD/lib/ollama/libcudart.so* /home/kozak23/.var/app/com.jeffser.Alpaca/cache/tmp/ollama/ollama2969286635/runners/cuda*/libcudart.so* /usr/local/cuda/lib64/libcudart.so* /usr/lib/x86_64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/x86_64-linux-gnu/libcudart.so* /usr/lib/wsl/lib/libcudart.so* /usr/lib/wsl/drivers/*/libcudart.so* /opt/cuda/lib64/libcudart.so* /usr/local/cuda*/targets/aarch64-linux/lib/libcudart.so* /usr/lib/aarch64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/aarch64-linux-gnu/libcudart.so* /usr/local/cuda/lib*/libcudart.so* /usr/lib*/libcudart.so* /usr/local/lib*/libcudart.so*]"
time=2024-09-12T09:03:25.168+01:00 level=DEBUG source=gpu.go:525 msg="discovered GPU libraries" paths="[/app/lib/ollama/libcudart.so.12.4.99 /app/lib/ollama/libcudart.so.11.3.109]"
cudaSetDevice err: 35
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=gpu.go:537 msg="Unable to load cudart" library=/app/lib/ollama/libcudart.so.12.4.99 error="your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
cudaSetDevice err: 35
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=gpu.go:537 msg="Unable to load cudart" library=/app/lib/ollama/libcudart.so.11.3.109 error="your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
time=2024-09-12T09:03:25.169+01:00 level=WARN source=amd_linux.go:59 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:127 msg="detected CPU /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/1/properties"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:217 msg="mapping amdgpu to drm sysfs nodes" amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties vendor=4098 device=29824 unique_id=0
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:251 msg=matched amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties drm=/sys/class/drm/card1/device
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:283 msg="amdgpu memory" gpu=0 total="8.0 GiB"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_linux.go:284 msg="amdgpu memory" gpu=0 available="7.4 GiB"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/lib/ollama"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/lib"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/GL/default/lib"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/openh264/extra"
time=2024-09-12T09:03:25.169+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/openh264/extra"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/sdk/llvm15/lib"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/GL/default/lib"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/ollama"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/plugins/AMD/lib/ollama"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /opt/rocm/lib"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib64"
time=2024-09-12T09:03:25.170+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/share/ollama/lib/rocm"
time=2024-09-12T09:03:25.170+01:00 level=WARN source=amd_linux.go:395 msg="amdgpu detected, but no compatible rocm library found.  Either install rocm v6, or follow manual install instructions at https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install"
time=2024-09-12T09:03:25.170+01:00 level=WARN source=amd_linux.go:322 msg="unable to verify rocm library, will use cpu" error="no suitable rocm found, falling back to CPU"
time=2024-09-12T09:03:25.170+01:00 level=INFO source=gpu.go:347 msg="no compatible GPUs were discovered"
time=2024-09-12T09:03:25.170+01:00 level=INFO source=types.go:107 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="62.7 GiB" available="59.3 GiB"
[GIN] 2024/09/12 - 09:03:25 | 200 |     491.746µs |       127.0.0.1 | GET      "/api/tags"

```

**Comment by ishaanbhimwal** [comment]
Same issue!

**Comment by Aleksanaa** [comment]
```
Traceback (most recent call last):
  File "/nix/store/gqrsn8v42fjzlx1g206lsywlawrkm3dd-alpaca-2.0.2/share/Alpaca/alpaca/dialogs.py", line 328, in <lambda>
    file_dialog.open(self, None, lambda file_dialog, result: attach_file_response(self, file_dialog, result))
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gqrsn8v42fjzlx1g206lsywlawrkm3dd-alpaca-2.0.2/share/Alpaca/alpaca/dialogs.py", line 321, in attach_file_response
    if file_type == 'image' and not self.verify_if_image_can_be_used():
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AlpacaWindow' object has no attribute 'verify_if_image_can_be_used'
```

Did you get this?

**Comment by Jeffser** [comment]
my bad, I forgot to change that line when I rewrote the model system

https://github.com/Jeffser/Alpaca/commit/cbdfe43896f2e65a3c4eabf8a278b21f1a6c762c

Should be fixed now
