### ISSUE TITLE
external instance doesn't work 

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#355]
**Describe the bug**
Alpaca detect downloaded model but doesn't display the model selector, the model details button doesn't work and Alpaca crash when I try installing model

**Expected behavior**
External instance work

**Screenshots**
[Capture vidéo du 2024-10-16 23-33-53.webm](https://github.com/user-attachments/assets/7399fad4-9ff7-467a-ac1f-050b37c163f2)

**Debugging information**
```
INFO	[main.py | main] Alpaca version: 2.6.5
INFO	[connection_handler.py | request] GET : http://127.0.0.1:11434//api/tags
INFO	[connection_handler.py | request] POST : http://127.0.0.1:11434//api/show
ERROR	[model_widget.py | add_model] Status code was 404
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 357, in show_information
    model_name = model.get_child().get_label()
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_child'
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 357, in show_information
    model_name = model.get_child().get_label()
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_child'
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 357, in show_information
    model_name = model.get_child().get_label()
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_child'
INFO	[model_widget.py | pull_model] Pulling model: qwen2.5:0.5b
INFO	[connection_handler.py | request] POST : http://127.0.0.1:11434//api/pull
INFO	[window.py | show_toast] Erreur lors du téléchargement de 'qwen2.5:0.5b'
ERROR	[window.py | connection_error] Connection error
INFO	[connection_handler.py | request] GET : http://127.0.0.1:11434//api/tags
INFO	[connection_handler.py | request] POST : http://127.0.0.1:11434//api/show
ERROR	[model_widget.py | add_model] Status code was 404
**
Adwaita:ERROR:../src/adw-dialog-host.c:164:dialog_closing_cb: assertion failed: (g_ptr_array_find (self->dialogs, dialog, &index))
Bail out! Adwaita:ERROR:../src/adw-dialog-host.c:164:dialog_closing_cb: assertion failed: (g_ptr_array_find (self->dialogs, dialog, &index))
```

**Comment by brunos3d** [comment]
Just remove the slash (/) at the end of your endpoint

![image](https://github.com/user-attachments/assets/92f8d805-0156-4255-a49c-e5b475cf71b8)

**Comment by loulou64490** [comment]
yep

**Comment by loulou64490** [comment]
@Jeffser 

It's would be better if the app accept the link with or without `https://` at the start or `/` at the end

**Comment by Jeffser** [comment]
makes sense, I will make a regex to check for those things

**Comment by Jeffser** [comment]
Easy fix, thanks for the suggestion

https://github.com/Jeffser/Alpaca/commit/28b2fbe45e95c2d2333e9b47117962194148f71b
