### ISSUE TITLE
Stuck at loading/writing manifest

### ISSUE THREAD

**Issue by ihatemakinganaccount** [Jeffser/Alpaca#377]
Alpaca 2.7.0 Flatpak, Fedora 41, Intel cpu only:

I am unable to add additional models. When trying to download one directly from the GUI selection, it downloads but at the end it gets stuck at "writing manifest" and never finishes. If I exit Alpaca, it deletes what it downloaded on next launch.

While when I try to add from name or from GGUF, it gets stuck at "loading manifest" and never starts the download or import. Tried this on a few models from huggingface which should be compatible, tho I can't be super sure since I can't use any to confirm.

I was able to download models on previous versions, but I've not tried importing before, so idk if that was working.

Last lines of debug launching Alpaca and trying to download Llama 3.2 1b:

`[GIN] 2024/11/20 - 09:27:55 | 200 |     777.253µs |       127.0.0.1 | GET      "/api/tags"
INFO	[connection_handler.py | request] POST : http://127.0.0.1:11435/api/show
[GIN] 2024/11/20 - 09:27:55 | 200 |   15.034288ms |       127.0.0.1 | POST     "/api/show"
INFO	[model_widget.py | pull_model] Pulling model: llama3.2:1b
INFO	[connection_handler.py | request] POST : http://127.0.0.1:11435/api/pull
time=2024-11-20T09:29:29.923+01:00 level=INFO source=download.go:175 msg="downloading 74701a8c35f6 in 14 100 MB part(s)"
time=2024-11-20T09:33:35.581+01:00 level=INFO source=download.go:175 msg="downloading 966de95ca8a6 in 1 1.4 KB part(s)"
time=2024-11-20T09:33:37.838+01:00 level=INFO source=download.go:175 msg="downloading fcc5a6bec9da in 1 7.7 KB part(s)"
time=2024-11-20T09:33:40.291+01:00 level=INFO source=download.go:175 msg="downloading a70ff7e570d9 in 1 6.0 KB part(s)"
time=2024-11-20T09:33:42.544+01:00 level=INFO source=download.go:175 msg="downloading 4f659a1e86d7 in 1 485 B part(s)"
[GIN] 2024/11/20 - 09:33:48 | 200 |         4m20s |       127.0.0.1 | POST     "/api/pull"`

Pulling a model from name shows the same thing except of the downloading part.

I also tried running Alpaca from cli and I found this when trying to add a model from name, might be relevant:

`[GIN] 2024/11/20 - 11:05:58 | 200 |   1.20513755s |       127.0.0.1 | POST     "/api/pull"
Exception in thread Thread-5 (pull_model):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 655, in pull_model
    response = window.ollama_instance.request("POST", "api/pull", json.dumps({"name": model_name}), lambda data: model.update(data))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/connection_handler.py", line 82, in request
    callback(json.loads(line.decode("utf-8")))
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 655, in <lambda>
    response = window.ollama_instance.request("POST", "api/pull", json.dumps({"name": model_name}), lambda data: model.update(data))
                                                                                                                 ^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 239, in update
    GLib.idle_add(self.prc_label.set_label, data['status'])
                                            ~~~~^^^^^^^^^^
KeyError: 'status'`

**Comment by ihatemakinganaccount** [comment]
Haven't seen this since I updated... Something, so I guess it's fine now.
