### ISSUE TITLE
alpaca_search_provider logs error "name 'APP_ID' is not defined"

### ISSUE THREAD

**Issue by darkblaze69** [Jeffser/Alpaca#398]
* GNOME 47.2
* Arch Linux
* alpaca-ai 2.9.0-3

Using AUR package on arch.

alpaca_search_provider logs error:

```
Dec 12 10:51:59 alpaca_search_provider[162104]: Exception while handling org.gnome.Shell.SearchProvider2.GetSubsearchResultSet()
Dec 12 10:51:59 alpaca_search_provider[162104]: Traceback (most recent call last):
Dec 12 10:51:59 alpaca_search_provider[162104]:   File "/usr/lib/python3.12/site-packages/pydbus/registration.py", line 81, in call_method
Dec 12 10:51:59 alpaca_search_provider[162104]:     result = method(*parameters, **kwargs)
Dec 12 10:51:59 alpaca_search_provider[162104]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 10:51:59 alpaca_search_provider[162104]:   File "/usr/bin/alpaca_search_provider", line 60, in GetSubsearchResultSet
Dec 12 10:51:59 alpaca_search_provider[162104]:     results = self.search_chats(terms)
Dec 12 10:51:59 alpaca_search_provider[162104]:               ^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 10:51:59 alpaca_search_provider[162104]:   File "/usr/bin/alpaca_search_provider", line 86, in search_chats
Dec 12 10:51:59 alpaca_search_provider[162104]:     if os.path.exists(os.path.join(get_data_dir(), "chats", "chats.json")):
Dec 12 10:51:59 alpaca_search_provider[162104]:                                    ^^^^^^^^^^^^^^
Dec 12 10:51:59 alpaca_search_provider[162104]:   File "/usr/bin/alpaca_search_provider", line 19, in get_data_dir
Dec 12 10:51:59 alpaca_search_provider[162104]:     path = os.path.join(base, APP_ID)
Dec 12 10:51:59 alpaca_search_provider[162104]:                               ^^^^^^
Dec 12 10:51:59 alpaca_search_provider[162104]: NameError: name 'APP_ID' is not defined
Dec 12 10:51:59 gnome-character[162635]: JS LOG: Characters Application started
Dec 12 10:51:59 gnome-shell[161190]: Received error from D-Bus search provider com.jeffser.Alpaca.desktop: Gio.IOErrorEnum: GDBus.Error:unknown.NameError: name 'APP_ID' is not defined
```

**Comment by Jeffser** [comment]
Hi, I changed the way the search provider works by using `alpaca --list-chats` instead of reading the list directly from the files, the affected code is no longer in use, thanks for the report!

https://github.com/Jeffser/Alpaca/commit/4197ee38ac66b80e5724464d5d3488eb694cbb66
