### ISSUE TITLE
App doesn't start after update

### ISSUE THREAD

**Issue by mrvladus** [Jeffser/Alpaca#71]
After update to 0.9.1 app is not starting. This error appears in output:
```
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/main.py", line 42, in do_activate
    win = AlpacaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 902, in __init__
    self.temperature_spin.set_value(data['model_tweaks']['temperature'])
                                    ~~~~^^^^^^^^^^^^^^^^
KeyError: 'model_tweaks'
```

Deleting app directory  `~/.var/app/com.jeffser.Alpaca` fixes issue.

**Comment by Jeffser** [comment]
My bad, thanks for reporting it
It is fixed
https://github.com/Jeffser/Alpaca/commit/725e0930fe36cbe055cdd0d01dc03810560dd7fa
