### ISSUE TITLE
Loading a custom GGUF model

### ISSUE THREAD

**Issue by topiga** [Jeffser/Alpaca#76]
**Is your feature request related to a problem? Please describe.**
Yes, this feature request is related to a problem (maybe specific to my use case). I can't load custom models from Alpaca.

**Describe the solution you'd like**
An easy way to import a model, in a GGUF format.
Maybe in the top left corner, a button to import a custom model.
![Capture d’écran du 2024-05-31 09-24-45](https://github.com/Jeffser/Alpaca/assets/38886040/790fceec-803e-4ff7-9315-e883faf2737c)

**Describe alternatives you've considered**
Using ollama, but nah, this app is fantastic (thanks btw)

**Comment by Jeffser** [comment]
Sounds good, I'm going to work on it for today's update

**Comment by Jeffser** [comment]
Hi, I kinda made it, it's still in testing but I will release it anyways, I'll polish it tomorrow

https://github.com/Jeffser/Alpaca/commit/c579e6ec999e5948584226cff6671f9748394a04

**Comment by tsilvs** [comment]
Can't load GGUFs from HuggingFace cloned `git-lfs` repos. Getting an error.

Here's the repo:

![Screenshot: TheBloke/Mistral-7B-Instruct-v0.2-GGUF repo](https://github.com/Jeffser/Alpaca/assets/26058495/17688278-cc1b-4db5-9391-78538cb41c8e)

<details>

<summary><code>tree</code></summary>

```
├── config.json
├── mistral-7b-instruct-v0.2.Q2_K.gguf
├── mistral-7b-instruct-v0.2.Q3_K_L.gguf
├── mistral-7b-instruct-v0.2.Q3_K_M.gguf
├── mistral-7b-instruct-v0.2.Q3_K_S.gguf
├── mistral-7b-instruct-v0.2.Q4_0.gguf
├── mistral-7b-instruct-v0.2.Q4_K_M.gguf
├── mistral-7b-instruct-v0.2.Q4_K_S.gguf
├── mistral-7b-instruct-v0.2.Q5_0.gguf
├── mistral-7b-instruct-v0.2.Q5_K_M.gguf
├── mistral-7b-instruct-v0.2.Q5_K_S.gguf
├── mistral-7b-instruct-v0.2.Q6_K.gguf
├── mistral-7b-instruct-v0.2.Q8_0.gguf
└── README.md
```

</details>

Here's how it looks like in the file picker in Alpaca:

![Screenshot: GGUF file picker in Alpaca](https://github.com/Jeffser/Alpaca/assets/26058495/41ad7973-773d-4500-a22e-e56ddf1c03da)

And here's what happens every time I try to load a `.gguf` file:

# Error

```
$> flatpak run com.jeffser.Alpaca
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
[GIN] 2024/06/05 - 14:59:43 | 200 |      83.043µs |       127.0.0.1 | GET      "/"
[GIN] 2024/06/05 - 14:59:43 | 200 |     452.025µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/06/05 - 14:59:48 | 200 |     243.962µs |       127.0.0.1 | GET      "/api/tags"
/app/share/Alpaca/alpaca/window.py:376: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  self.create_model_name.set_text(name)
[GIN] 2024/06/05 - 15:00:07 | 200 |    1.766126ms |       127.0.0.1 | POST     "/api/create"
[GIN] 2024/06/05 - 15:00:07 | 200 |     173.282µs |       127.0.0.1 | GET      "/api/tags"
Stopped Alpaca's Ollama instance
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
**
Adwaita:ERROR:../src/adw-dialog-host.c:164:dialog_closing_cb: assertion failed: (g_ptr_array_find (self->dialogs, dialog, &index))
Bail out! Adwaita:ERROR:../src/adw-dialog-host.c:164:dialog_closing_cb: assertion failed: (g_ptr_array_find (self->dialogs, dialog, &index))
```

**Comment by Jeffser** [comment]
I'll take a look at that later today, thanks for reporting it

**Comment by VipinVIP** [comment]
On a related note (possibly) , while loading a GGUF model , I got this error 

```
INFO	[main.py | main] Alpaca version: 1.0.5
INFO	[local_instance.py | start] Starting Alpaca's Ollama instance...
INFO	[local_instance.py | start] Started Alpaca's Ollama instance
[GIN] 2024/08/03 - 18:59:07 | 200 |      158.64µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/08/03 - 18:59:07 | 200 |     142.822µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/08/03 - 18:59:10 | 200 |     171.765µs |       127.0.0.1 | GET      "/api/tags"
/app/share/Alpaca/alpaca/window.py:446: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  self.create_model_name.set_text(model.split("/")[-1].split(".")[0])
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/dialogs.py", line 251, in create_model_from_file_response
    self.create_model(file.get_path(), True)
  File "/app/share/Alpaca/alpaca/window.py", line 447, in create_model
    self.create_model_base.set_subtitle(self.convert_model_name(model, 1))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 420, in convert_model_name
    if mode == 1: return "{}:{}".format(name.split(" (")[0].replace(" ", "-").lower(), name.split(" (")[1][:-1])
                                                                                       ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/dialogs.py", line 258, in <lambda>
    file_dialog.open(self, None, lambda file_dialog, result: create_model_from_file_response(self, file_dialog, result))
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/dialogs.py", line 253, in create_model_from_file_response
    self.logger.error(e)
    ^^^^^^^^^^^
AttributeError: 'AlpacaWindow' object has no attribute 'logger'
```

**Comment by Jeffser** [comment]
welp that's just my bad code, it tries to log the error but I wrote that line badly, still I think I know what's going on there, I'm going to fix it

**Comment by Jeffser** [comment]
Hi, GGUF support has been fixed!

https://github.com/Jeffser/Alpaca/commit/7440fa5a375e5b3cef38d3de1ccba75beb3d68d4
