### ISSUE TITLE
Ollama server doesn't start

### ISSUE THREAD

**Issue by topiga** [Jeffser/Alpaca#77]
**Describe the bug**
Can't download a model, and if tried, the app crashes after attempting to do so.

**Expected behavior**
Being able to pull a model, and use it.

**Additional context**
This is the backtrace :
```
: No such file or directory.
/tmp/ollama1963609681/runners/cpu_avx2/ollama_llama_server: No such file or directory.
Downloading executable for /tmp/ollama1963609681/runners/cpu_avx2/ollama_llama_server...
warning: Can't open file /tmp/ollama1963609681/runners/cpu_avx2/ollama_llama_server during file-backed mapping note processing
Downloading executable for /usr/lib/x86_64-linux-gnu/libc.so.6...
warning: Can't open file /usr/lib/x86_64-linux-gnu/libc.so.6 during file-backed mapping note processing
Downloading executable for /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32...
warning: Can't open file /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32 during file-backed mapping note processing
Downloading executable for /usr/lib/x86_64-linux-gnu/libpthread.so.0...
warning: Can't open file /usr/lib/x86_64-linux-gnu/libpthread.so.0 during file-backed mapping note processing
Downloading executable for /usr/lib/x86_64-linux-gnu/libgcc_s.so.1...
warning: Can't open file /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 during file-backed mapping note processing
Downloading executable for /usr/lib/x86_64-linux-gnu/libm.so.6...
warning: Can't open file /usr/lib/x86_64-linux-gnu/libm.so.6 during file-backed mapping note processing
Downloading executable for /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2...
warning: Can't open file /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 during file-backed mapping note processing
[New LWP 46]
[New LWP 48]
[New LWP 51]
[New LWP 49]
[New LWP 47]
[New LWP 54]
[New LWP 50]
[New LWP 53]
[New LWP 52]
Missing separate debuginfo for the main executable file.
The debuginfo package for this file is probably broken.
Downloading separate debug info for system-supplied DSO at 0x7ffc0d8a5000...
Core was generated by `/tmp/ollama1963609681/runners/cpu_avx2/ollama_llama_server --model /home/topiga'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f02768a3e14 in ?? ()
[Current thread is 1 (LWP 46)]

Thread 1 (LWP 46):
#0  0x00007f02768a3e14 in ?? ()
No symbol table info available.
#1  0x00007f0276be5196 in ?? ()
No symbol table info available.
#2  0x12f7f327a51a7b00 in ?? ()
No symbol table info available.
#3  0x00007f02769f2563 in ?? ()
No symbol table info available.
#4  0x0000000000000006 in ?? ()
No symbol table info available.
#5  0x00007f0276ced780 in ?? ()
No symbol table info available.
#6  0x0000000001dd4d20 in ?? ()
No symbol table info available.
#7  0x00007ffc0d81c178 in ?? ()
No symbol table info available.
#8  0x000000000000008a in ?? ()
No symbol table info available.
#9  0x00007ffc0d81c010 in ?? ()
No symbol table info available.
#10 0x00007f0276851dce in ?? ()
No symbol table info available.
#11 0x00007ffc0d81c040 in ?? ()
No symbol table info available.
#12 0x00007f02769f2b50 in ?? ()
No symbol table info available.
#13 0x00007ffc0d81c0d0 in ?? ()
No symbol table info available.
#14 0x00007f027683983f in ?? ()
No symbol table info available.
#15 0x0000000000000020 in ?? ()
No symbol table info available.
#16 0x00007f0276ced780 in ?? ()
No symbol table info available.
#17 0x00007ffc0d81c178 in ?? ()
No symbol table info available.
#18 0x000000000000008a in ?? ()
No symbol table info available.
#19 0x00007ffc0d81c060 in ?? ()
No symbol table info available.
#20 0x00007f0276898ef1 in ?? ()
No symbol table info available.
#21 0x00007ffc0d81c0a0 in ?? ()
No symbol table info available.
#22 0x00007f02769f24e0 in ?? ()
No symbol table info available.
#23 0x00007ffc0d81c090 in ?? ()
No symbol table info available.
#24 0x00007f027689946b in ?? ()
No symbol table info available.
#25 0x0000000000000001 in ?? ()
No symbol table info available.
#26 0x00007f02769f24e0 in ?? ()
No symbol table info available.
#27 0x000000000000000a in ?? ()
No symbol table info available.
#28 0x00007f0276ced780 in ?? ()
No symbol table info available.
#29 0x00007ffc0d81c0d0 in ?? ()
No symbol table info available.
#30 0x00007f0276895332 in ?? ()
No symbol table info available.
#31 0x00007ffc0d81c0d0 in ?? ()
No symbol table info available.
#32 0x00007f027688d05c in ?? ()
No symbol table info available.
#33 0x0000000001f2d8e8 in ?? ()
No symbol table info available.
#34 0x12f7f327a51a7b00 in ?? ()
No symbol table info available.
#35 0x0000000001f2d8e8 in ?? ()
No symbol table info available.
#36 0x000000000070ec00 in ?? ()
No symbol table info available.
#37 0x00007ffc0d81c110 in ?? ()
No symbol table info available.
#38 0x00007f0276aace03 in ?? ()
No symbol table info available.
#39 0x00000000021bd350 in ?? ()
No symbol table info available.
#40 0x12f7f327a51a7b00 in ?? ()
No symbol table info available.
#41 0x0000000000000002 in ?? ()
No symbol table info available.
#42 0x0000000001d84920 in ?? ()
No symbol table info available.
#43 0x0000000001dd34a0 in ?? ()
No symbol table info available.
#44 0x0000000001d84920 in ?? ()
No symbol table info available.
#45 0x00007ffc0d81c120 in ?? ()
No symbol table info available.
#46 0x00007f0276abfbfa in ?? ()
No symbol table info available.
#47 0x00007ffc0d81c130 in ?? ()
No symbol table info available.
#48 0x00007f0276abfc65 in ?? ()
No symbol table info available.
#49 0x00007ffc0d81c150 in ?? ()
No symbol table info available.
#50 0x00007f0276abff40 in ?? ()
No symbol table info available.
#51 0x0000000001dd34a0 in ?? ()
No symbol table info available.
#52 0x000000000070ebe0 in ?? ()
No symbol table info available.
#53 0x00007ffc0d81c1b0 in ?? ()
No symbol table info available.
#54 0x000000000042cd55 in ?? ()
No symbol table info available.
#55 0x3239323939353538 in ?? ()
No symbol table info available.
#56 0x0000000001dd32b0 in ?? ()
No symbol table info available.
#57 0x0000000070747468 in ?? ()
No symbol table info available.
#58 0x0000000001dd32c8 in ?? ()
No symbol table info available.
#59 0x6d616e74736f6820 in ?? ()
No symbol table info available.
#60 0x00007ffc0d81ced8 in ?? ()
No symbol table info available.
#61 0x00007ffc0d81c3d0 in ?? ()
No symbol table info available.
#62 0x00007ffc0d81c210 in ?? ()
No symbol table info available.
#63 0x00007ffc0d81d3a0 in ?? ()
No symbol table info available.
#64 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 48):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 51):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 49):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 5 (LWP 47):
#0  0x00007f027692b6bd in ?? ()
No symbol table info available.
#1  0x00007ffc0d81c6e0 in ?? ()
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 6 (LWP 54):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 7 (LWP 50):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 8 (LWP 53):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 9 (LWP 52):
#0  0x00007f027689e709 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
warning: Could not load shared library symbols for 5 libraries, e.g. /usr/lib/x86_64-linux-gnu/libstdc++.so.6.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
From                To                  Syms Read   Shared Object Library
                                        No          /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                                        No          /usr/lib/x86_64-linux-gnu/libm.so.6
                                        No          /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
                                        No          /usr/lib/x86_64-linux-gnu/libpthread.so.0
                                        No          /usr/lib/x86_64-linux-gnu/libc.so.6
0x00007f0276e11000  0x00007f0276e37f55  No          /lib64/ld-linux-x86-64.so.2
No symbol "__abort_msg" in current context.
No symbol "__glib_assert_msg" in current context.
rax            0x0                 0
rbx            0x2e                46
rcx            0x7f02768a3e14      139648555433492
rdx            0x6                 6
rsi            0x2e                46
rdi            0x2e                46
rbp            0x7ffc0d81bff0      0x7ffc0d81bff0
rsp            0x7ffc0d81bfb0      0x7ffc0d81bfb0
r8             0x0                 0
r9             0x7ffc0d81bb50      140720535092048
r10            0x8                 8
r11            0x246               582
r12            0x7f0276ced780      139648559929216
r13            0x1dd4d20           31280416
r14            0x6                 6
r15            0x8a                138
rip            0x7f02768a3e14      0x7f02768a3e14
eflags         0x246               [ PF ZF IF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
st0            0                   (raw 0x00000000000000000000)
st1            0                   (raw 0x00000000000000000000)
st2            0                   (raw 0x00000000000000000000)
st3            0                   (raw 0x00000000000000000000)
st4            0                   (raw 0x00000000000000000000)
st5            0                   (raw 0x00000000000000000000)
st6            0                   (raw 0x00000000000000000000)
st7            0                   (raw 0x00000000000000000000)
fctrl          0x37f               895
fstat          0x0                 0
ftag           0xffff              65535
fiseg          0x0                 0
fioff          0x0                 0
foseg          0x0                 0
fooff          0x0                 0
fop            0x0                 0
mxcsr          0x1fbb              [ IE DE OE UE PE IM DM ZM OM UM PM ]
bndcfgu        {raw = 0x0, config = {base = 0x0, reserved = 0x0, preserved = 0x0, enabled = 0x0}} {raw = 0x0, config = {base = 0, reserved = 0, preserved = 0, enabled = 0}}
bndstatus      {raw = 0x0, status = {bde = 0x0, error = 0x0}} {raw = 0x0, status = {bde = 0, error = 0}}
fs_base        0x7f0276ced780      139648559929216
gs_base        0x0                 0
ymm0           {v16_bfloat16 = {0x2563, 0x769f, 0x7f02, 0x0 <repeats 13 times>}, v16_half = {0x2563, 0x769f, 0x7f02, 0x0 <repeats 13 times>}, v8_float = {0x769f2563, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x7f02769f2563, 0x0, 0x0, 0x0}, v32_int8 = {0x63, 0x25, 0x9f, 0x76, 0x2, 0x7f, 0x0 <repeats 26 times>}, v16_int16 = {0x2563, 0x769f, 0x7f02, 0x0 <repeats 13 times>}, v8_int32 = {0x769f2563, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x7f02769f2563, 0x0, 0x0, 0x0}, v2_int128 = {0x7f02769f2563, 0x0}}
ymm1           {v16_bfloat16 = {0x2563, 0x769f, 0x7f02, 0x0, 0x2563, 0x769f, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0x2563, 0x769f, 0x7f02, 0x0, 0x2563, 0x769f, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0x769f2563, 0x7f02, 0x769f2563, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x7f02769f2563, 0x7f02769f2563, 0x0, 0x0}, v32_int8 = {0x63, 0x25, 0x9f, 0x76, 0x2, 0x7f, 0x0, 0x0, 0x63, 0x25, 0x9f, 0x76, 0x2, 0x7f, 0x0 <repeats 18 times>}, v16_int16 = {0x2563, 0x769f, 0x7f02, 0x0, 0x2563, 0x769f, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x769f2563, 0x7f02, 0x769f2563, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x7f02769f2563, 0x7f02769f2563, 0x0, 0x0}, v2_int128 = {0x7f02769f256300007f02769f2563, 0x0}}
ymm2           {v16_bfloat16 = {0x0 <repeats 16 times>}, v16_half = {0x0 <repeats 16 times>}, v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm3           {v16_bfloat16 = {0x0, 0x0, 0x0, 0x0, 0xfef0, 0x76ab, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0x0, 0x0, 0x0, 0x0, 0xfef0, 0x76ab, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0x0, 0x0, 0x76abfef0, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x7f0276abfef0, 0x0, 0x0}, v32_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf0, 0xfe, 0xab, 0x76, 0x2, 0x7f, 0x0 <repeats 18 times>}, v16_int16 = {0x0, 0x0, 0x0, 0x0, 0xfef0, 0x76ab, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x0, 0x0, 0x76abfef0, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x7f0276abfef0, 0x0, 0x0}, v2_int128 = {0x7f0276abfef00000000000000000, 0x0}}
ymm4           {v16_bfloat16 = {0x0, 0x0, 0x0, 0x4000, 0x0 <repeats 12 times>}, v16_half = {0x0, 0x0, 0x0, 0x4000, 0x0 <repeats 12 times>}, v8_float = {0x0, 0x40000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x4000000000000000, 0x0, 0x0, 0x0}, v32_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0 <repeats 24 times>}, v16_int16 = {0x0, 0x0, 0x0, 0x4000, 0x0 <repeats 12 times>}, v8_int32 = {0x0, 0x40000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x4000000000000000, 0x0, 0x0, 0x0}, v2_int128 = {0x4000000000000000, 0x0}}
ymm5           {v16_bfloat16 = {0x0, 0x76a0, 0x7f02, 0x0, 0x5180, 0x76c8, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0x0, 0x76a0, 0x7f02, 0x0, 0x5180, 0x76c8, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0x76a00000, 0x7f02, 0x76c85180, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x7f0276a00000, 0x7f0276c85180, 0x0, 0x0}, v32_int8 = {0x0, 0x0, 0xa0, 0x76, 0x2, 0x7f, 0x0, 0x0, 0x80, 0x51, 0xc8, 0x76, 0x2, 0x7f, 0x0 <repeats 18 times>}, v16_int16 = {0x0, 0x76a0, 0x7f02, 0x0, 0x5180, 0x76c8, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x76a00000, 0x7f02, 0x76c85180, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x7f0276a00000, 0x7f0276c85180, 0x0, 0x0}, v2_int128 = {0x7f0276c8518000007f0276a00000, 0x0}}
ymm6           {v16_bfloat16 = {0x5030, 0x76e0, 0x7f02, 0x0, 0x3664, 0x76c3, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0x5030, 0x76e0, 0x7f02, 0x0, 0x3664, 0x76c3, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0x76e05030, 0x7f02, 0x76c33664, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x7f0276e05030, 0x7f0276c33664, 0x0, 0x0}, v32_int8 = {0x30, 0x50, 0xe0, 0x76, 0x2, 0x7f, 0x0, 0x0, 0x64, 0x36, 0xc3, 0x76, 0x2, 0x7f, 0x0 <repeats 18 times>}, v16_int16 = {0x5030, 0x76e0, 0x7f02, 0x0, 0x3664, 0x76c3, 0x7f02, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x76e05030, 0x7f02, 0x76c33664, 0x7f02, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x7f0276e05030, 0x7f0276c33664, 0x0, 0x0}, v2_int128 = {0x7f0276c3366400007f0276e05030, 0x0}}
ymm7           {v16_bfloat16 = {0xc0a0, 0xd81, 0x7ffc, 0x0, 0xc0a8, 0xd81, 0x7ffc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0xc0a0, 0xd81, 0x7ffc, 0x0, 0xc0a8, 0xd81, 0x7ffc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0xd81c0a0, 0x7ffc, 0xd81c0a8, 0x7ffc, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x7ffc0d81c0a0, 0x7ffc0d81c0a8, 0x0, 0x0}, v32_int8 = {0xa0, 0xc0, 0x81, 0xd, 0xfc, 0x7f, 0x0, 0x0, 0xa8, 0xc0, 0x81, 0xd, 0xfc, 0x7f, 0x0 <repeats 18 times>}, v16_int16 = {0xc0a0, 0xd81, 0x7ffc, 0x0, 0xc0a8, 0xd81, 0x7ffc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0xd81c0a0, 0x7ffc, 0xd81c0a8, 0x7ffc, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x7ffc0d81c0a0, 0x7ffc0d81c0a8, 0x0, 0x0}, v2_int128 = {0x7ffc0d81c0a800007ffc0d81c0a0, 0x0}}
ymm8           {v16_bfloat16 = {0x3120, 0x202c, 0x2c31, 0x3120, 0x202c, 0x2c31, 0x3120, 0x202c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0x3120, 0x202c, 0x2c31, 0x3120, 0x202c, 0x2c31, 0x3120, 0x202c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0x202c3120, 0x31202c31, 0x2c31202c, 0x202c3120, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x31202c31202c3120, 0x202c31202c31202c, 0x0, 0x0}, v32_int8 = {0x20, 0x31, 0x2c, 0x20, 0x31, 0x2c, 0x20, 0x31, 0x2c, 0x20, 0x31, 0x2c, 0x20, 0x31, 0x2c, 0x20, 0x0 <repeats 16 times>}, v16_int16 = {0x3120, 0x202c, 0x2c31, 0x3120, 0x202c, 0x2c31, 0x3120, 0x202c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x202c3120, 0x31202c31, 0x2c31202c, 0x202c3120, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x31202c31202c3120, 0x202c31202c31202c, 0x0, 0x0}, v2_int128 = {0x202c31202c31202c31202c31202c3120, 0x0}}
ymm9           {v16_bfloat16 = {0x4, 0x0, 0x0, 0x0, 0x4, 0x0 <repeats 11 times>}, v16_half = {0x4, 0x0, 0x0, 0x0, 0x4, 0x0 <repeats 11 times>}, v8_float = {0x4, 0x0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x4, 0x4, 0x0, 0x0}, v32_int8 = {0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4, 0x0 <repeats 23 times>}, v16_int16 = {0x4, 0x0, 0x0, 0x0, 0x4, 0x0 <repeats 11 times>}, v8_int32 = {0x4, 0x0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x4, 0x4, 0x0, 0x0}, v2_int128 = {0x40000000000000004, 0x0}}
ymm10          {v16_bfloat16 = {0x2, 0x0, 0x0, 0x0, 0x2, 0x0 <repeats 11 times>}, v16_half = {0x2, 0x0, 0x0, 0x0, 0x2, 0x0 <repeats 11 times>}, v8_float = {0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x2, 0x2, 0x0, 0x0}, v32_int8 = {0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0 <repeats 23 times>}, v16_int16 = {0x2, 0x0, 0x0, 0x0, 0x2, 0x0 <repeats 11 times>}, v8_int32 = {0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x2, 0x2, 0x0, 0x0}, v2_int128 = {0x20000000000000002, 0x0}}
ymm11          {v16_bfloat16 = {0x10, 0x0, 0x0, 0x0, 0x10, 0x0 <repeats 11 times>}, v16_half = {0x10, 0x0, 0x0, 0x0, 0x10, 0x0 <repeats 11 times>}, v8_float = {0x10, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x10, 0x10, 0x0, 0x0}, v32_int8 = {0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0 <repeats 23 times>}, v16_int16 = {0x10, 0x0, 0x0, 0x0, 0x10, 0x0 <repeats 11 times>}, v8_int32 = {0x10, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x10, 0x10, 0x0, 0x0}, v2_int128 = {0x100000000000000010, 0x0}}
ymm12          {v16_bfloat16 = {0xfa, 0xfe, 0x0, 0x0, 0xfb, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v16_half = {0xfa, 0xfe, 0x0, 0x0, 0xfb, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_float = {0xfe00fa, 0x0, 0xff00fb, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0xfe00fa, 0xff00fb, 0x0, 0x0}, v32_int8 = {0xfa, 0x0, 0xfe, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfb, 0x0, 0xff, 0x0 <repeats 21 times>}, v16_int16 = {0xfa, 0xfe, 0x0, 0x0, 0xfb, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0xfe00fa, 0x0, 0xff00fb, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0xfe00fa, 0xff00fb, 0x0, 0x0}, v2_int128 = {0xff00fb0000000000fe00fa, 0x0}}
ymm13          {v16_bfloat16 = {0xf9, 0xfb, 0xfd, 0xff, 0x0 <repeats 12 times>}, v16_half = {0xf9, 0xfb, 0xfd, 0xff, 0x0 <repeats 12 times>}, v8_float = {0xfb00f9, 0xff00fd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0xff00fd00fb00f9, 0x0, 0x0, 0x0}, v32_int8 = {0xf9, 0x0, 0xfb, 0x0, 0xfd, 0x0, 0xff, 0x0 <repeats 25 times>}, v16_int16 = {0xf9, 0xfb, 0xfd, 0xff, 0x0 <repeats 12 times>}, v8_int32 = {0xfb00f9, 0xff00fd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0xff00fd00fb00f9, 0x0, 0x0, 0x0}, v2_int128 = {0xff00fd00fb00f9, 0x0}}
ymm14          {v16_bfloat16 = {0x0 <repeats 16 times>}, v16_half = {0x0 <repeats 16 times>}, v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm15          {v16_bfloat16 = {0x0 <repeats 16 times>}, v16_half = {0x0 <repeats 16 times>}, v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
bnd0           {lbound = 0x0, ubound = 0xffffffffffffffff} : size 0xffffffffffffffff {lbound = 0x0, ubound = 0xffffffffffffffff} : size -1
bnd1           {lbound = 0x0, ubound = 0xffffffffffffffff} : size 0xffffffffffffffff {lbound = 0x0, ubound = 0xffffffffffffffff} : size -1
bnd2           {lbound = 0x0, ubound = 0xffffffffffffffff} : size 0xffffffffffffffff {lbound = 0x0, ubound = 0xffffffffffffffff} : size -1
bnd3           {lbound = 0x0, ubound = 0xffffffffffffffff} : size 0xffffffffffffffff {lbound = 0x0, ubound = 0xffffffffffffffff} : size -1
No function contains program counter for selected frame.

```

**Comment by Jeffser** [comment]
hi, that looks like an Ollama issue more than an Alpaca issue
